### PR TITLE
Tidy indentation

### PR DESCRIPTION
**Pull request by AidanNairn**
Used Beautify package in atom to automatically adjust the HTML indentation.

### CODE REVIEW

**Comment by jon-atto-bennett** [comment]
Hi Aedan, have had a look at the file  after the "fix indentation" commit, I hope that is the right one. All the indentation is spot on but I have the following comments based on this resource https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/ 

- Recommended that indentation consists of 2 spaces to prevent code spreading out to much. So ensure tab is set to 2 spaces or use the spacebar.

- paragraphs should be treated as block level elements e.g. 
<p> 
    Lorem ipsum. 
</p>

- Avoid  unnecessary line spaces, only use to separate distinct blocks of code.

Hope this makes sense  and is only my take on what I've learnt being very new to all this :)

**Comment by AidanNairn** [comment]
Hey Jon, thanks for the feedback. I'd like to fix a couple of things before you approve the pull (specifically the second comment you mentioned about the paragraphs being treated as block level elements). Could you clarify what you mean by indentation should consist of two spaces?

**Comment by AidanNairn** [comment]
Looks like I may have fixed the majority of the things you mentioned. It definitely looks easier to read. That article you sent me was very useful so thank you again.

**Comment by jon-atto-bennett** [comment]
Hi Aidan
<p>
  Blah blah blah
</p>

Hope that makes sense, a quick Sunday drink has turned into a bit of a session :)

Cheers

Jon

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jon-atto-bennett** [comment]
Bugger that didn't come out as I wanted it to. Basically it is recommended that you use two taps of the space bar for an indent, the tab key may give you more than that depending on how it's configured.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by AidanNairn** [comment]
Yep, I see what you mean! I think I've fixed that part of the file. If you're still out drinking don't worry about checking it right now. Enjoy yourself!

**Comment by jon-atto-bennett** [comment]
All good I'll check it tomorrow morning

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jon-atto-bennett** [comment]
Hi Aidan, sorry about the delay but reviewed the code and it looks good so here's my approval 👍 Not 100% sure what happens next but I think you merge the pull request and then I delete the branch, but happy to be corrected.

**Pull request merged**
